# -*- coding: utf-8 -*-
"""YBI Project.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eXcwCoocduHEw7wFkDZBQvxJg2kCFY5f
"""

import pandas as pd

cement = pd.read_csv("https://github.com/YBI-Foundation/Dataset/raw/main/Concrete%20Compressive%20Strength.csv")

cement

cement.head()

cement.info()

cement.describe()

cement.columns

y=cement['Concrete Compressive Strength(MPa, megapascals) ']
X = cement[['Cement (kg in a m^3 mixture)',
       'Blast Furnace Slag (kg in a m^3 mixture)',
       'Fly Ash (kg in a m^3 mixture)', 'Water (kg in a m^3 mixture)',
       'Superplasticizer (kg in a m^3 mixture)',
       'Coarse Aggregate (kg in a m^3 mixture)',
       'Fine Aggregate (kg in a m^3 mixture)', 'Age (day)',]]

from sklearn.model_selection import train_test_split 
X_train,X_test,Y_train,y_test = train_test_split(X,y)

from sklearn.linear_model import LinearRegression

LinearRegression()

model=LinearRegression()

model.fit(X_train,Y_train)

y_predict = model.predict(X_test)

from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(y_test,y_predict)



"""# New section"""